# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon,QPixmap,QPalette,QBrush

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(660, 660)
        widget.setMinimumSize(QtCore.QSize(605, 500))
        widget.setMaximumSize(QtCore.QSize(660, 660))

        # 背景图片
        palette1 = QPalette()
        pix = QPixmap('D:\Learn-python-notes\projects\demo\Calculator\photos\starrySky.jpg')
        pix = pix.scaled(660, 660)
        palette1.setBrush(QPalette.Background, QBrush(pix))
        widget.setPalette(palette1)
        # 左上角图标
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap("D:\Learn-python-notes\projects\demo\Calculator\photos\calc1.png"), QtGui.QIcon.Normal,
                            QtGui.QIcon.Off)
        widget.setWindowIcon(self.icon)

        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 580, 376))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setTabletTracking(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_6.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_6.addWidget(self.pushButton_26)
        self.pushButton_28 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_6.addWidget(self.pushButton_28)
        self.pushButton_27 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_6.addWidget(self.pushButton_27)
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout_6.addWidget(self.pushButton_29)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_4.addWidget(self.pushButton_21)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_3.addWidget(self.pushButton_22)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_3.addWidget(self.pushButton_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout.addWidget(self.pushButton_23)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout.addWidget(self.pushButton_19)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_5.addWidget(self.pushButton_24)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_5.addWidget(self.pushButton_15)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_5.addWidget(self.pushButton_20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_2.addWidget(self.pushButton_30)

        self.retranslateUi(widget)
        self.pushButton_30.clicked.connect(self.textEdit_2.clear)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Caculator"))
        self.pushButton_25.setText(_translate("widget", "sqrt"))
        self.pushButton_26.setText(_translate("widget", "log"))
        self.pushButton_28.setText(_translate("widget", "mod"))
        self.pushButton_27.setText(_translate("widget", "del"))
        self.pushButton_29.setText(_translate("widget", "÷"))
        self.pushButton_21.setText(_translate("widget", "Π"))
        self.pushButton_11.setText(_translate("widget", "7"))
        self.pushButton_12.setText(_translate("widget", "8"))
        self.pushButton_13.setText(_translate("widget", "9"))
        self.pushButton_17.setText(_translate("widget", "×"))
        self.pushButton_22.setText(_translate("widget", "n!"))
        self.pushButton_6.setText(_translate("widget", "4"))
        self.pushButton_9.setText(_translate("widget", "5"))
        self.pushButton_10.setText(_translate("widget", "6"))
        self.pushButton_18.setText(_translate("widget", "-"))
        self.pushButton_23.setText(_translate("widget", "pow"))
        self.pushButton_3.setText(_translate("widget", "1"))
        self.pushButton_4.setText(_translate("widget", "2"))
        self.pushButton_5.setText(_translate("widget", "3"))
        self.pushButton_19.setText(_translate("widget", "+"))
        self.pushButton_24.setText(_translate("widget", "("))
        self.pushButton_16.setText(_translate("widget", ")"))
        self.pushButton_14.setText(_translate("widget", "0"))
        self.pushButton_15.setText(_translate("widget", "."))
        self.pushButton_20.setText(_translate("widget", "="))
        self.pushButton_30.setText(_translate("widget", "Clear"))


