# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication,QMainWindow,QFileDialog,QWidget
from PyQt5.QtGui import QPalette,QPixmap
from PyQt5.QtCore import Qt


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 852)
        MainWindow.setMaximumSize(1048,852)
        #设置窗口透明度
        MainWindow.setWindowOpacity(0.9)
        #设置背景色
        palette = QPalette()
        MainWindow.setAutoFillBackground(True)
        palette.setColor(QPalette.Window,Qt.lightGray)
        MainWindow.setPalette(palette)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/平台运行动态.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 881, 721))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(600, 600))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.image_label = QtWidgets.QLabel(self.groupBox)
        self.image_label.setObjectName("image_label")
        self.gridLayout.addWidget(self.image_label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 20))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 540, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen_O = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_O.setIcon(icon1)
        self.actionOpen_O.setObjectName("actionOpen_O")
        self.actionSave_S = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/保存 (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_S.setIcon(icon2)
        self.actionSave_S.setObjectName("actionSave_S")
        self.actionExit_E = QtWidgets.QAction(MainWindow)
        self.actionExit_E.setObjectName("actionExit_E")
        self.action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/保存 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon3)
        self.action.setObjectName("action")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/搜索.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSearch.setIcon(icon4)
        self.actionSearch.setObjectName("actionSearch")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionsetting = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsetting.setIcon(icon5)
        self.actionsetting.setObjectName("actionsetting")
        self.menuFile.addAction(self.actionOpen_O)
        self.menuFile.addAction(self.actionSave_S)
        self.menuFile.addAction(self.action)
        self.menuFile.addAction(self.actionExit_E)
        self.menuView.addAction(self.actionSearch)
        self.menuSetting.addAction(self.actionsetting)
        self.menuSetting.addAction(self.actionabout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.toolBar.addAction(self.actionOpen_O)
        self.toolBar.addAction(self.actionSave_S)
        self.toolBar.addAction(self.actionSearch)
        self.toolBar_2.addAction(self.action)
        #关联信号
        self.actionOpen_O.triggered.connect(self.openImage)
        self.actionSave_S.triggered.connect(self.saveImage)
        self.pushButton.clicked.connect(self.openImage)
        self.pushButton_2.clicked.connect(self.saveImage)
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.actionExit_E.triggered.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片浏览器"))
        self.groupBox.setTitle(_translate("MainWindow", "图片显示区"))
        self.image_label.setText(_translate("MainWindow", ""))
        self.groupBox_2.setTitle(_translate("MainWindow", "图片信息"))
        self.label.setText(_translate("MainWindow", "size"))
        self.label_2.setText(_translate("MainWindow", "rate"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        self.pushButton_2.setText(_translate("MainWindow", "Save"))
        self.pushButton_3.setText(_translate("MainWindow", "Exit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Test"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionOpen_O.setText(_translate("MainWindow", "Open(&O)"))
        self.actionSave_S.setText(_translate("MainWindow", "Save(&S)"))
        self.actionExit_E.setText(_translate("MainWindow", "Exit(&E)"))
        self.action.setText(_translate("MainWindow", "Upload(&U)"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionsetting.setText(_translate("MainWindow", "setting"))

    def openImage(self):
        file, _ = QFileDialog.getOpenFileName(self, '打开图片', '.', '图像文件(*.png *.jpg *.ico)')
        self.image_label.setPixmap(QPixmap(file))


    def saveImage(self):
        path,_ = QFileDialog.getSaveFileName(self,'保存图片','D:','ALL Files(*);;png(*.png);;jpg(*.jpg)')
        pass



if __name__ =='__main__':
    app = QApplication(sys.argv)
    window = QMainWindow()
    ui =  Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())

